apiVersion: v1
kind: Service
metadata:
  name: {{ include "web.fullname" . }}-service2
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app: {{ include "web.name" . }}2